// pipeline {
//     agent {
//         docker {
//             image 'node:6-alpine'
//             args '-p 3000:3000'
//         }
//     }
//     environment {
//         CI = 'true'
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'npm install'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh './jenkins/scripts/test.sh'
//             }
//         }
//         stage('Deliver') {
//             steps {
//                 sh './jenkins/scripts/deliver.sh'
//                 input message: 'Finished using the web site? (Click "Proceed" to continue)'
//                 sh './jenkins/scripts/kill.sh'
//             }
//         }
//     }
// }

// stage('Sonarqube') {
        //     agent { 
        //         docker 'openjdk:8-jre' 
        //     }
        //     environment {
        //         scannerHome = tool 'SonarQubeScanner'
        //     }
        //     steps {
        //         sh 'java -version'
        //         withSonarQubeEnv('sonarqube') {
        //             sh "${scannerHome}/bin/sonar-scanner -X"
        //         }
        //         timeout(time: 10, unit: 'MINUTES') {
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
        // }
        
        // old deliver stage
        // stage('Deliver') { 
        //     agent {
        //         docker {
        //             image 'node:6-alpine'
        //             args '-p 3000:3000'
        //         }
        //     }
        //     steps {
        //         sh './jenkins/scripts/deliver.sh' 
        //         sh './jenkins/scripts/kill.sh' 
        //     }
        // }
